// Font
import { Inter } from "next/font/google";

// CSS
import "./globals.css";

// Components
import Navbar from "@/components/Navbar";
import Nav from "@/components/Nav";
import Navbrand from "@/components/Navbrand";

// Config
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Navbar>
            <Navbrand />
            <Nav />
          </Navbar>
        </header>

        {children}
      </body>
    </html>
  );
}
